version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Activating virtualenv
          command: |
            sudo apt-get update; sudo apt-get install libmemcached-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Check linting
          command: |
            . venv/bin/activate
            black --check --exclude venv .
            curlylint forum/templates/
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py collectstatic
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py test
